[package]
authors = ["Erik Johnston"]
name = "synapse-compress-state"
version = "0.1.0"
description = "A tool to compress some state in a Synapse instance's database"

[dependencies]
clap = "2.32.0"
fallible-iterator = "0.1.5"
indicatif = "0.9.0"
postgres = "0.15.2"
rayon = "1.0.2"

[dependencies.rust-matrix-lib]
git = "https://github.com/erikjohnston/rust-matrix-lib"
