[package]
authors = ["Erik Johnston"]
description = "A tool to compress some state in a Synapse instance's database"
name = "synapse-compress-state"
version = "0.1.0"
edition = "2018"

[dependencies]
clap = "2.33.0"
indicatif = "0.15.0"
jemallocator = "0.3.2"
openssl = "0.10.32"
postgres = "0.19.0"
postgres-openssl = "0.5.0"
rand = "0.8.0"
rayon = "1.3.0"
string_cache = "0.8.0"

[dependencies.state-map]
git = "https://github.com/matrix-org/rust-matrix-state-map"
